### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by elementalPRESS** [julianpoemp/ngx-jodit#29]
Hi,

I've discovered a new issue where I'm not really sure whether it's related to Jodit or to ngx-jodit. When I try to upload an image via the UI (independent if selecting an image via the file browser or via drag&drop) I always get the following error. 

    TypeError: Cannot read properties of undefined (reading 'forImageChangeAttributes')
        at Selection.insertImage (selection.js:585:30)
        at config.js:69:25
        at Array.forEach (<anonymous>)
        at Jodit.defaultHandlerSuccess (config.js:59:24)
        at Uploader.<anonymous> (file-selector.js:35:25)
        at reader.onloadend (send-files.js:41:37)
        at _ZoneDelegate.invoke (zone.js:368:26)
        at Object.onInvoke (core.mjs:14778:33)
        at _ZoneDelegate.invoke (zone.js:367:52)
        at Zone.runGuarded (zone.js:139:47)
        
Jodit Version: 4.0.0-beta.119
ngx-jodit:  3.0.0-beta.9
Browser: Chrome 121
OS: Mac
Angular: 17.1

Thx for your help!
Cheers,
Lars

**Comment by julianpoemp** [comment]
@elementalPRESS can you please update to the latest version of ngx-jodit v3 and jodit v4? both are out as stable versions now. Please tell me, if the error still exists with these versions.

**Comment by elementalPRESS** [comment]
> @elementalPRESS can you please update to the latest version of ngx-jodit v3 and jodit v4? both are out as stable versions now. Please tell me, if the error still exists with these versions.

Hi Julian, thx for your advice. That worked for me! Interestingly, an `npm outdated` didn’t show me the updates, so I wasn't aware of the updates. After a manual installation of the latest versions everything is find now.

**Comment by julianpoemp** [comment]
@elementalPRESS great! If you like this project please consider giving this repository a star ;)

**Comment by elementalPRESS** [comment]
> @elementalPRESS great! If you like this project please consider giving this repository a star ;)

Sure! Done! ;-)
